#!/usr/bin/env node
const items = [
    // "airbnb",
    // "facebook",
    // "aws",
    // "microsoft",
    // "twitter",
    // "youtube",
    // "facebookincubator",
    // "amzn",
    // "palantir",
    // "paypal",
    // "fivethirtyeight",
    // "lyft",
    // "uber",
    // "postmates",
    // "venmo",
    // "teslamotors",
    // "github",
    // "stripe",
    // "redfin",
    // "zillow",
    // "dotnet",
    // "digitalocean",
    // "instructure",
    // "23andme",
    // "robinhood",
    // "jetbrains",
    // "nfl",
    // "box",
    // "dropbox",
    // "ebay",
    // "hulu",
    // "netflix",
    // "google",
    // "yelp",
    // "adobe",
    // "libertymutual",
    // "linkedin",
    // "ibm",
    // "mozilla",
    // "intel",
    // "hewlettpackard",
    // "ciscosystems",
    // "oracle",
    // "att",
    // "apple",
    // "symantec",
    // "nvidia",
    // "cfpb",
    // "ersi",
    // "square",
    // "gilt",
    // "guardian",
    // "shopify",
    // "sap",
    // "artsy",
    // "apache",
    // "codrops",
    // "googlesamples",
    // "mapbox",
    // "spring-projects",
    "thoughtbot",
    // "angular",
    // "googlecloudplatform",
    // "awslabs",
    // "yahoo",
    // "atom",
    // "openstack",
    // "elastic",
    // "npm",
    // "fortawesome",
    // "docker",
    "vmware",
    "janestreet",
    "scikit-learn",
    "JuliaLang",
    "haskell",
    "elm-lang",
    "spring-framework",
    "Symantec",
    "spotify",
    "riotgames",
    "slackhq",
    "bloomberg",
    "discordapp",
    "graphql",
    "justintv",
    "elastic",
    "wework",
    "pinterest",
    "cloudera",
    "docusign",
    "pivotal",
    "coinbase",
];

const fetch = require('node-fetch');

items.forEach(function(acc) {
   const url = "https://api.gitin.tech/account?account=" + acc;
   console.log(url);
   fetch(url, { method: 'POST'})
    .then(res => {
        console.log(res);
    });
});
